In [39]:
class par:
    def __init__(self,a,b):
        self.a = a
        self.b = b

class child(par):
    def __init__(self,a,b):
        super(child,self).__init__(a,b)
        
chi1=child(10,20)

In [116]:
import torch
import torch.nn as nn
a=torch.randn(2,10)
print(f'a=\n{a}')
b=torch.randn(2,10)
print(f'b=\n{b}')
c=torch.mul(a,b)
#print(torch.log(a)*b)
a=nn.functional.softmax(a,dim=-1)
print(f'after a=\n{a}')

a=
tensor([[ 0.8830, -0.8265,  0.6362, -0.4201, -0.2250, -1.4247, -0.6597,  1.5984,
          0.2875,  1.5997],
        [ 3.8289,  0.4250,  0.4108,  1.2038,  2.3458, -2.2086,  0.4905,  1.6665,
         -0.9503, -0.4359]])
b=
tensor([[ 0.0607,  0.3049,  0.5939,  1.3977,  0.7941, -0.8824,  0.2194,  0.8692,
          0.5795,  0.6582],
        [-0.0560, -0.6084,  0.5360, -1.0408, -0.4995, -0.7207,  0.4404,  0.7315,
          0.4114,  0.5191]])
after a=
tensor([[0.1330, 0.0241, 0.1039, 0.0361, 0.0439, 0.0132, 0.0284, 0.2719, 0.0733,
         0.2722],
        [0.6490, 0.0216, 0.0213, 0.0470, 0.1473, 0.0015, 0.0230, 0.0747, 0.0055,
         0.0091]])
